//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFacturesCat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eFacturesCat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--&lt;xs:schema xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.facturae.es/Facturae/2009/v3.2/Facturae&quot; targetNamespace=&quot;http://www.facturae.es/Facturae/2009/v3.2/Facturae&quot; version=&quot;3.2&quot;--&gt;
        ///  &lt;xs:schema xmlns:fb2b=&quot;http://www.facturae.es/Facturae/Extensions/FB2B&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.facturae.es/Facturae/2009/v3.2/Facturae&quot; targetNamespace=&quot;http://www.facturae.es/Fact [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Facturaev3_2 {
            get {
                return ResourceManager.GetString("Facturaev3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     
        ///&lt;xs:schema 
        ///xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; 
        ///xmlns=&quot;http://www.facturae.es/Facturae/Extensions/FB2B&quot; 
        ///targetNamespace=&quot;http://www.facturae.es/Facturae/Extensions/FB2B&quot; version=&quot;1.0&quot;&gt;
        ///
        ///    &lt;xs:element name=&quot;FaceB2BExtension&quot;&gt;
        ///        &lt;xs:annotation&gt;
        ///            &lt;xs:documentation xml:lang=&quot;es&quot;&gt;Elemento ORIGEN de la extensión de FaceB2B que permite especificar undiades
        ///            del Directorio de Entidades DIRe como Centros Administrativos. &lt;/xs:documentation&gt;
        ///        &lt;/xs:annotati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fb2b_extension {
            get {
                return ResourceManager.GetString("fb2b_extension", resourceCulture);
            }
        }
    }
}
