//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFacturesCat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eFacturesCat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- ====================================================================== --&gt;
        ///&lt;!-- ===== CCTS Core Component Type Schema Module ===== --&gt;
        ///&lt;!-- ====================================================================== --&gt;
        ///&lt;!--
        ///   Module of Core Component Type
        ///   Agency: UN/CEFACT
        ///   VersionID: 1.1
        ///   Last change: 14 January 2005
        ///   
        ///   
        ///   
        ///   Copyright (C) UN/CEFACT (2006). All Rights Reserved.
        ///   This document and translations of it may be copied and furnished to other [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CCTS_CCT_SchemaModule_2_1 {
            get {
                return ResourceManager.GetString("CCTS_CCT_SchemaModule_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--&lt;xs:schema xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.facturae.es/Facturae/2009/v3.2/Facturae&quot; targetNamespace=&quot;http://www.facturae.es/Facturae/2009/v3.2/Facturae&quot; version=&quot;3.2&quot;--&gt;
        ///  &lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.facturae.es/Facturae/2009/v3.2/Facturae&quot; targetNamespace=&quot;http://www.facturae.es/Facturae/2009/v3.2/Facturae&quot; version=&quot;3.2&quot;&gt;
        ///    &lt;!--xs:import na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Facturaev3_2 {
            get {
                return ResourceManager.GetString("Facturaev3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.facturae.es/Facturae/2014/v3.2.1/Facturae&quot; targetNamespace=&quot;http://www.facturae.es/Facturae/2014/v3.2.1/Facturae&quot; version=&quot;3.2.1&quot; xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://www.w3.org/2000/09/xmldsig#&quot; schemaLocation=&quot;xmldsig-core-schema.xsd&quot;/&gt;
        ///	&lt;xs:element name=&quot;Facturae&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation xml:lang=&quot;en&quot;&gt; Element ORIGIN of Facturae Invoi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Facturaev3_2_1 {
            get {
                return ResourceManager.GetString("Facturaev3_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.facturae.gob.es/formato/Versiones/Facturaev3_2_2.xml&quot; targetNamespace=&quot;http://www.facturae.gob.es/formato/Versiones/Facturaev3_2_2.xml&quot; version=&quot;3.2.2&quot; xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://www.w3.org/2000/09/xmldsig#&quot; schemaLocation=&quot;xmldsig-core-schema.xsd&quot;/&gt;
        ///	&lt;xs:element name=&quot;Facturae&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation xml:lang=&quot;en&quot;&gt; Element OR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Facturaev3_2_2 {
            get {
                return ResourceManager.GetString("Facturaev3_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     
        ///&lt;xs:schema 
        ///xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; 
        ///xmlns=&quot;http://www.facturae.es/Facturae/Extensions/FB2B&quot; 
        ///targetNamespace=&quot;http://www.facturae.es/Facturae/Extensions/FB2B&quot; version=&quot;1.0&quot;&gt;
        ///
        ///    &lt;xs:element name=&quot;FaceB2BExtension&quot;&gt;
        ///        &lt;xs:annotation&gt;
        ///            &lt;xs:documentation xml:lang=&quot;es&quot;&gt;Elemento ORIGEN de la extensión de FaceB2B que permite especificar undiades
        ///            del Directorio de Entidades DIRe como Centros Administrativos. &lt;/xs:documentation&gt;
        ///        &lt;/xs:annotati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fb2b_extension {
            get {
                return ResourceManager.GetString("fb2b_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;xs:schema
        ///xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///xmlns=&quot;http://www.facturae.es/Facturae/Extensions/FaceB2BExtensionv1_1&quot;
        ///targetNamespace=&quot;http://www.facturae.es/Facturae/Extensions/FaceB2BExtensionv1_1&quot; version=&quot;1.1&quot;&gt;
        ///
        ///    &lt;xs:element name=&quot;FaceB2BExtension&quot;&gt;
        ///        &lt;xs:annotation&gt;
        ///            &lt;xs:documentation xml:lang=&quot;es&quot;&gt;Elemento ORIGEN de la extensión de FaceB2B que permite especificar undiades
        ///            del Directorio de Entidades DIRe como Centros Administrativos. &lt;/xs: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fb2b_extensionv_1_1 {
            get {
                return ResourceManager.GetString("fb2b_extensionv_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--
        ///  Library:           OASIS Universal Business Language (UBL) 2.1 OS
        ///                     http://docs.oasis-open.org/ubl/os-UBL-2.1/
        ///  Release Date:      04 November 2013
        ///  Module:            xsd/common/UBL-CommonAggregateComponents-2.1.xsd
        ///  Generated on:      2013-10-31 17:17z
        ///  Copyright (c) OASIS Open 2013. All Rights Reserved.
        ///--&gt;
        ///&lt;xsd:schema xmlns=&quot;urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2&quot;
        ///            xmlns:cac=&quot;urn:oasis:names [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UBL_CommonAggregateComponents_2_1 {
            get {
                return ResourceManager.GetString("UBL_CommonAggregateComponents_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--
        ///  Library:           OASIS Universal Business Language (UBL) 2.1 OS
        ///                     http://docs.oasis-open.org/ubl/os-UBL-2.1/
        ///  Release Date:      04 November 2013
        ///  Module:            xsd/common/UBL-CommonBasicComponents-2.1.xsd
        ///  Generated on:      2013-10-31 17:17z
        ///  Copyright (c) OASIS Open 2013. All Rights Reserved.
        ///--&gt;
        ///&lt;xsd:schema xmlns=&quot;urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2&quot;
        ///            xmlns:qdt=&quot;urn:oasis:names:specifi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UBL_CommonBasicComponents_2_1 {
            get {
                return ResourceManager.GetString("UBL_CommonBasicComponents_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--
        ///  Library:           OASIS Universal Business Language (UBL) 2.1 OS
        ///                     http://docs.oasis-open.org/ubl/os-UBL-2.1/
        ///  Release Date:      04 November 2013
        ///  Module:            UBL-CommonExtensionComponents-2.1.xsd
        ///  Generated on:      2013-04-20 18:40(UTC)
        ///  Copyright (c) OASIS Open 2013. All Rights Reserved.
        ///--&gt;
        ///&lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; 
        ///xmlns=&quot;urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UBL_CommonExtensionComponents_2_1 {
            get {
                return ResourceManager.GetString("UBL_CommonExtensionComponents_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--
        ///  Library:           OASIS Universal Business Language (UBL) 2.1 OS
        ///                     http://docs.oasis-open.org/ubl/os-UBL-2.1/
        ///  Release Date:      04 November 2013
        ///  Module:            xsd/common/UBL-CommonSignatureComponents-2.1.xsd
        ///  Generated on:      2013-10-31 17:18z
        ///  Copyright (c) OASIS Open 2013. All Rights Reserved.
        ///--&gt;
        ///&lt;xsd:schema xmlns=&quot;urn:oasis:names:specification:ubl:schema:xsd:CommonSignatureComponents-2&quot;
        ///            xmlns:sac=&quot;urn:oasis:names [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UBL_CommonSignatureComponents_2_1 {
            get {
                return ResourceManager.GetString("UBL_CommonSignatureComponents_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--
        ///  Library:           OASIS Universal Business Language (UBL) 2.1 OS
        ///                     http://docs.oasis-open.org/ubl/os-UBL-2.1/
        ///  Release Date:      04 November 2013
        ///  Module:            UBL-CoreComponentParameters-2.1.xsd
        ///  Generated on:      2013-04-20 18:40(UTC)
        ///  Copyright (c) OASIS Open 2013. All Rights Reserved.
        ///--&gt;
        ///&lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///            targetNamespace=&quot;urn:un:unece:uncefact:documentation:2&quot;
        ///            xml [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UBL_CoreComponentParameters_2_1 {
            get {
                return ResourceManager.GetString("UBL_CoreComponentParameters_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--
        ///  Library:           OASIS Universal Business Language (UBL) 2.1 OS
        ///                     http://docs.oasis-open.org/ubl/os-UBL-2.1/
        ///  Release Date:      04 November 2013
        ///  Module:            UBL-ExtensionContentDataType-2.1.xsd
        ///  Generated on:      2013-04-20 18:40(UTC)
        ///  Copyright (c) OASIS Open 2013. All Rights Reserved.
        ///--&gt;
        ///&lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=
        ///     &quot;urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponent [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UBL_ExtensionContentDataType_2_1 {
            get {
                return ResourceManager.GetString("UBL_ExtensionContentDataType_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--
        ///  Library:           OASIS Universal Business Language (UBL) 2.1 OS
        ///                     http://docs.oasis-open.org/ubl/os-UBL-2.1/
        ///  Release Date:      04 November 2013
        ///  Module:            xsd/maindoc/UBL-Invoice-2.1.xsd
        ///  Generated on:      2013-10-31 17:17z
        ///  Copyright (c) OASIS Open 2013. All Rights Reserved.
        ///--&gt;
        ///&lt;xsd:schema xmlns=&quot;urn:oasis:names:specification:ubl:schema:xsd:Invoice-2&quot;
        ///            xmlns:cac=&quot;urn:oasis:names:specification:ubl:schema:xsd:Commo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UBL_Invoice_2_1 {
            get {
                return ResourceManager.GetString("UBL_Invoice_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--
        ///  Library:           OASIS Universal Business Language (UBL) 2.1 OS
        ///                     http://docs.oasis-open.org/ubl/os-UBL-2.1/
        ///  Release Date:      04 November 2013
        ///  Module:            xsd/maindoc/UBL-Invoice-2.1.xsd
        ///  Generated on:      2013-10-31 17:17z
        ///  Copyright (c) OASIS Open 2013. All Rights Reserved.
        ///--&gt;
        ///&lt;xsd:schema xmlns=&quot;urn:oasis:names:specification:ubl:schema:xsd:Invoice-2&quot;
        ///            xmlns:cac=&quot;urn:oasis:names:specification:ubl:schema:xsd:Commo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UBL_Invoice_2_11 {
            get {
                return ResourceManager.GetString("UBL_Invoice_2_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--
        ///  Library:           OASIS Universal Business Language (UBL) 2.1 OS
        ///                     http://docs.oasis-open.org/ubl/os-UBL-2.1/
        ///  Release Date:      04 November 2013
        ///  Module:            UBL-QualifiedDataTypes-2.1.xsd
        ///  Generated on:      2013-04-20 18:40(UTC)
        ///  Copyright (c) OASIS Open 2013. All Rights Reserved.
        ///--&gt;
        ///&lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    targetNamespace=&quot;urn:oasis:names:specification:ubl:schema:xsd:QualifiedDataTypes-2&quot;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UBL_QualifiedDataTypes_2_1 {
            get {
                return ResourceManager.GetString("UBL_QualifiedDataTypes_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--
        ///  Library:           OASIS Universal Business Language (UBL) 2.1 OS
        ///                     http://docs.oasis-open.org/ubl/os-UBL-2.1/
        ///  Release Date:      04 November 2013
        ///  Module:            xsd/common/UBL-SignatureAggregateComponents-2.1.xsd
        ///  Generated on:      2013-10-31 17:18z
        ///  Copyright (c) OASIS Open 2013. All Rights Reserved.
        ///--&gt;
        ///&lt;xsd:schema xmlns=&quot;urn:oasis:names:specification:ubl:schema:xsd:SignatureAggregateComponents-2&quot;
        ///            xmlns:sac=&quot;urn:oasis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UBL_SignatureAggregateComponents_2_1 {
            get {
                return ResourceManager.GetString("UBL_SignatureAggregateComponents_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--
        ///  Library:           OASIS Universal Business Language (UBL) 2.1 OS
        ///                     http://docs.oasis-open.org/ubl/os-UBL-2.1/
        ///  Release Date:      04 November 2013
        ///  Module:            xsd/common/UBL-SignatureBasicComponents-2.1.xsd
        ///  Generated on:      2013-10-31 17:18z
        ///  Copyright (c) OASIS Open 2013. All Rights Reserved.
        ///--&gt;
        ///&lt;xsd:schema xmlns=&quot;urn:oasis:names:specification:ubl:schema:xsd:SignatureBasicComponents-2&quot;
        ///            xmlns:qdt=&quot;urn:oasis:names:s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UBL_SignatureBasicComponents_2_1 {
            get {
                return ResourceManager.GetString("UBL_SignatureBasicComponents_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--
        ///  Library:           OASIS Universal Business Language (UBL) 2.1 OS
        ///                     http://docs.oasis-open.org/ubl/os-UBL-2.1/
        ///  Release Date:      04 November 2013
        ///  Module:            UBL-UnqualifiedDataTypes-2.1.xsd
        ///  Generated on:      2013-04-20 18:40(UTC)
        ///  Copyright (c) OASIS Open 2013. All Rights Reserved.
        ///
        ///  This schema fragment implements UBL unqualified datatypes using core
        ///  component types with all supplementary components as described in
        ///  CCTS  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UBL_UnqualifiedDataTypes_2_1 {
            get {
                return ResourceManager.GetString("UBL_UnqualifiedDataTypes_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--
        ///  Library:           OASIS Universal Business Language (UBL) 2.1 OS
        ///                     http://docs.oasis-open.org/ubl/os-UBL-2.1/
        ///  Release Date:      04 November 2013
        ///  Module:            UBL-XAdESv132-2.1.xsd
        ///  Generated on:      2011-02-21 17:20(UTC)
        ///
        ///  This is a copy of http://uri.etsi.org/01903/v1.3.2/XAdES.xsd modified 
        ///  only to change the importing URI for the XML DSig schema.
        ///--&gt;
        ///&lt;xsd:schema targetNamespace=&quot;http://uri.etsi.org/01903/v1.3.2#&quot; xmlns:xsd= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UBL_XAdESv132_2_1 {
            get {
                return ResourceManager.GetString("UBL_XAdESv132_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--
        ///  Library:           OASIS Universal Business Language (UBL) 2.1 OS
        ///                     http://docs.oasis-open.org/ubl/os-UBL-2.1/
        ///  Release Date:      04 November 2013
        ///  Module:            UBL-XAdESv141-2.1.xsd
        ///  Generated on:      2011-02-21 17:20(UTC)
        ///
        ///  This is a copy of http://uri.etsi.org/01903/v1.4.1/XAdESv141.xsd modified
        ///  only to change the importing URI for the XAdES v1.3.2 schema.
        ///--&gt;
        ///&lt;xsd:schema targetNamespace=&quot;http://uri.etsi.org/01903/v1.4.1#&quot; xml [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UBL_XAdESv141_2_1 {
            get {
                return ResourceManager.GetString("UBL_XAdESv141_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!--
        ///  Library:           OASIS Universal Business Language (UBL) 2.1 OS
        ///                     http://docs.oasis-open.org/ubl/os-UBL-2.1/
        ///  Release Date:      04 November 2013
        ///  Module:            UBL-xmldsig-core-schema-2.1.xsd
        ///  Generated on:      2010-08-13 19:10(UTC)
        ///
        ///  This is a copy of http://www.w3.org/TR/xmldsig-core/xmldsig-core-schema.xsd
        ///  modified only to remove these PUBLIC and SYSTEM identifiers from the DOCTYPE:
        ///
        ///        PUBLIC &quot;-//W3C//DTD XMLSchema 2001 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UBL_xmldsig_core_schema_2_1 {
            get {
                return ResourceManager.GetString("UBL_xmldsig_core_schema_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.facturae.es/Facturae/Extensions/Utilities&quot; targetNamespace=&quot;http://www.facturae.es/Facturae/Extensions/Utilities&quot;&gt;
        ///	&lt;xs:element name=&quot;UtilitiesExtension&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation xml:lang=&quot;en&quot;&gt; Element ORIGIN of Utilities Extension. &lt;/xs:documentation&gt;
        ///			&lt;xs:documentation xml:lang=&quot;es&quot;&gt; Elemento ORIGEN de la Extension de las Utilities. &lt;/xs:documentation&gt;
        ///		&lt;/xs:annotation&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UtilitiesExtension {
            get {
                return ResourceManager.GetString("UtilitiesExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- Schema for XML Signatures
        ///    http://www.w3.org/2000/09/xmldsig#
        ///    $Revision: 1.1 $ on $Date: 2002/02/08 20:32:26 $ by $Author: reagle $
        ///
        ///    Copyright 2001 The Internet Society and W3C (Massachusetts Institute
        ///    of Technology, Institut National de Recherche en Informatique et en
        ///    Automatique, Keio University). All Rights Reserved.
        ///    http://www.w3.org/Consortium/Legal/
        ///
        ///    This document is governed by the W3C Software License [1] as described
        ///    in the  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xmldsig_core_schema {
            get {
                return ResourceManager.GetString("xmldsig_core_schema", resourceCulture);
            }
        }
    }
}
