//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFacturesCat2Facturae32.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eFacturesCat2Facturae32.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;gc:CodeList xmlns:gc=&quot;http://genericode.org/2006/ns/CodeList/0.4/&quot;&gt;
        ///   &lt;Identification&gt;
        ///      &lt;ShortName&gt;CountryIdentificationCode&lt;/ShortName&gt;
        ///      &lt;LongName xml:lang=&quot;en&quot;&gt;Country&lt;/LongName&gt;
        ///      &lt;LongName Identifier=&quot;listID&quot;&gt;ISO3166-1&lt;/LongName&gt;
        ///      &lt;Version&gt;0.3&lt;/Version&gt;
        ///      &lt;CanonicalUri&gt;urn:oasis:names:specification:ubl:codelist:gc:CountryIdentificationCode&lt;/CanonicalUri&gt;
        ///      &lt;CanonicalVersionUri&gt;urn:oasis:names:specification:ubl:codelist:gc:C [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string CountryIdentificationCode_2_0_facturae30 {
            get {
                return ResourceManager.GetString("CountryIdentificationCode_2_0_facturae30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;!--
        ///	$Id: eFacturesCatUBL2_1Facturae3_2.xsl,v 1.0 2012/03/27 10:15:21 Santi Casas $
        ///	
        ///	ConversiÃ³n de facturas en formato UBL 2.1 a formato Facturae 3.2
        ///--&gt;
        ///&lt;!--
        ///	Basado en el trabajo realizado previamente por Oriol Bausa de Invinet (Thx!!)
        ///
        ///--&gt;
        ///&lt;!--  xmlns:ubl=&quot;urn:oasis:names:specification:ubl:schema:xsd:Invoice-2&quot; --&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; 
        ///	xmlns:ubl=&quot;urn:eFacturesCat:specification:schema:xsd:eFacturesCat-Invoice&quot;
        ///	xmlns:facturae=&quot;http:// [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string eFacturesCatUBL2_1Facturae3_2 {
            get {
                return ResourceManager.GetString("eFacturesCatUBL2_1Facturae3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        ///&lt;!--
        ///	$Id: InvinetUBL2Facturae3-cac.xsl,v 1.0 2008/02/22 10:15:21 Oriol Bausa $
        ///	
        ///	ConversiÃ³n de facturas en formato UBL 2.0 a formato Facturae 3.1
        ///	ConversiÃ³n de Common Aggregate Components
        ///--&gt;
        ///&lt;!--
        ///	Copyright (C) - Invinet Sistemes 2003, SL
        ///	- http://www.invinet.org/
        ///
        ///--&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:ubl=&quot;urn:oasis:names:specification:ubl:schema:xsd:Invoice-2&quot; 
        ///	xmlns:facturae=&quot;http://www.facturae.es/Facturae/2009/v3.2/Facturae&quot; 
        ///	xmlns:xs [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string eFacturesCatUBL2_1Facturae3_2_cac {
            get {
                return ResourceManager.GetString("eFacturesCatUBL2_1Facturae3_2_cac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        ///&lt;!--
        ///	$Id: InvinetUBL2Facturae3-cbc.xsl,v 1.0 2008/02/22 10:15:21 Oriol Bausa $
        ///	
        ///	ConversiÃƒÂƒÃ‚Â³n de facturas en formato UBL 2.0 a formato Facturae 3.1
        ///	ConversiÃƒÂƒÃ‚Â³n de Common Basic Components
        ///--&gt;
        ///&lt;!--
        ///	Copyright (C) - Invinet Sistemes 2003, SL
        ///	- http://www.invinet.org/
        ///
        ///--&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:ubl=&quot;urn:oasis:names:specification:ubl:schema:xsd:Invoice-2&quot; 
        ///	xmlns:facturae=&quot;http://www.facturae.es/Facturae/2009/v3.2/Facturae&quot; 
        ///	 [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string eFacturesCatUBL2_1Facturae3_2_cbc {
            get {
                return ResourceManager.GetString("eFacturesCatUBL2_1Facturae3_2_cbc", resourceCulture);
            }
        }
    }
}
